                <div class="cleared"></div>
                </div>

		<div class="cleared"></div>
    </div>
</div>

                          <div class="cleared"></div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="rnut-footer">
                <div class="rnut-footer-body">
                    <a href="#" class="rnut-rss-tag-icon" title="RSS"></a>
                            <div class="rnut-footer-text"><font size="3">
								<p><?php echo $mess_header1?></p>
								<p>พัฒนาโปรแกรม โดย : <font color="ffff00"> นายอนัตชัย  เกตุแก้ว</font></p>
								<p><font color="334455"> สำนักงานส่งเสริมการเรียนรู้จังหวัดสุราษฎร์ธานี</font></p>
                                                                <p>Copyright © 2016. All Rights Reserved.&nbsp;&nbsp;<font color="00ff33"> update 16 ตุลาคม 2559</font></p>
								<p><font color="00ff33"> Update 1 เมษายน 2569 โดย สำนักงานส่งเสริมการเรียนรู้ประจำจังหวัดนครศรีธรรมราช </font></p>
								<p>&nbsp;</p>
								</font>
                            </div>
                    <div class="cleared"></div>
                </div>
            </div>
    		<div class="cleared"></div>
        </div>
    </div>

</div>
